export const FETCH_PRODUCTS = "FETCH_PRODUCTS";
export const PRODUCTS_LOADING = "PRODUCTS_LOADING";
export const PRODUCTS_ERROR = "PRODUCTS_ERROR";
export const FETCH_SINGLE_PRODUCT = "FETCH_SINGLE_PRODUCT";