export const ADD_TO_FAVORITES = "ADD_TO_FAVORITES";
export const REMOVE_FROM_FAVORITES = "REMOVE_FROM_FAVORITES";
export const FETCH_FAVORITES = "FETCH_FAVORITES";
export const FAVORITES_LOADING = "FAVORITES_LOADING";